// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO ai_conversations (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, messages, context_snapshot, message_count, created_at, updated_at
`

type CreateConversationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.UserID, arg.Title)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.ContextSnapshot,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM ai_conversations WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, messages, context_snapshot, message_count, created_at, updated_at FROM ai_conversations WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.ContextSnapshot,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, message_count, created_at, updated_at
FROM ai_conversations
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2
`

type ListConversationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListConversationsRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	MessageCount int32              `json:"message_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationMessages = `-- name: UpdateConversationMessages :one
UPDATE ai_conversations
SET messages = $3,
    message_count = $4,
    title = COALESCE($5, title)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, messages, context_snapshot, message_count, created_at, updated_at
`

type UpdateConversationMessagesParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Messages     []byte      `json:"messages"`
	MessageCount int32       `json:"message_count"`
	Title        pgtype.Text `json:"title"`
}

func (q *Queries) UpdateConversationMessages(ctx context.Context, arg UpdateConversationMessagesParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, updateConversationMessages,
		arg.ID,
		arg.UserID,
		arg.Messages,
		arg.MessageCount,
		arg.Title,
	)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.ContextSnapshot,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
