// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetAllocation = `-- name: CreateBudgetAllocation :one
INSERT INTO budget_allocations (budget_id, category_id, amount)
VALUES ($1, $2, $3)
RETURNING id, budget_id, category_id, amount, created_at, updated_at
`

type CreateBudgetAllocationParams struct {
	BudgetID   pgtype.UUID    `json:"budget_id"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateBudgetAllocation(ctx context.Context, arg CreateBudgetAllocationParams) (BudgetAllocation, error) {
	row := q.db.QueryRow(ctx, createBudgetAllocation, arg.BudgetID, arg.CategoryID, arg.Amount)
	var i BudgetAllocation
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllocationsByBudget = `-- name: DeleteAllocationsByBudget :exec
DELETE FROM budget_allocations WHERE budget_id = $1
`

func (q *Queries) DeleteAllocationsByBudget(ctx context.Context, budgetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllocationsByBudget, budgetID)
	return err
}

const getAllocationByCategoryAndBudget = `-- name: GetAllocationByCategoryAndBudget :one
SELECT ba.amount FROM budget_allocations ba
WHERE ba.budget_id = $1 AND ba.category_id = $2
`

type GetAllocationByCategoryAndBudgetParams struct {
	BudgetID   pgtype.UUID `json:"budget_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) GetAllocationByCategoryAndBudget(ctx context.Context, arg GetAllocationByCategoryAndBudgetParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAllocationByCategoryAndBudget, arg.BudgetID, arg.CategoryID)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const getBudgetByUserID = `-- name: GetBudgetByUserID :one
SELECT id, user_id, global_amount, cycle_start_day, is_active, created_at, updated_at FROM budgets
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetBudgetByUserID(ctx context.Context, userID pgtype.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByUserID, userID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GlobalAmount,
		&i.CycleStartDay,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetAllocations = `-- name: ListBudgetAllocations :many
SELECT ba.id, ba.budget_id, ba.category_id, ba.amount, ba.created_at, ba.updated_at, bc.name AS category_name, bc.emoji AS category_emoji
FROM budget_allocations ba
JOIN budget_categories bc ON bc.id = ba.category_id
WHERE ba.budget_id = $1
ORDER BY bc.name ASC
`

type ListBudgetAllocationsRow struct {
	ID            pgtype.UUID        `json:"id"`
	BudgetID      pgtype.UUID        `json:"budget_id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  string             `json:"category_name"`
	CategoryEmoji string             `json:"category_emoji"`
}

func (q *Queries) ListBudgetAllocations(ctx context.Context, budgetID pgtype.UUID) ([]ListBudgetAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listBudgetAllocations, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetAllocationsRow{}
	for rows.Next() {
		var i ListBudgetAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (user_id, global_amount, cycle_start_day)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET global_amount = EXCLUDED.global_amount,
    cycle_start_day = EXCLUDED.cycle_start_day,
    is_active = TRUE
RETURNING id, user_id, global_amount, cycle_start_day, is_active, created_at, updated_at
`

type UpsertBudgetParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	GlobalAmount  pgtype.Numeric `json:"global_amount"`
	CycleStartDay int16          `json:"cycle_start_day"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.UserID, arg.GlobalAmount, arg.CycleStartDay)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GlobalAmount,
		&i.CycleStartDay,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
