// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNotificationSent = `-- name: CheckNotificationSent :one
SELECT EXISTS(
    SELECT 1 FROM budget_notifications
    WHERE user_id = $1
      AND category_id = $2
      AND cycle_start = $3
      AND threshold = $4
) AS sent
`

type CheckNotificationSentParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	CycleStart pgtype.Date `json:"cycle_start"`
	Threshold  int16       `json:"threshold"`
}

func (q *Queries) CheckNotificationSent(ctx context.Context, arg CheckNotificationSentParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationSent,
		arg.UserID,
		arg.CategoryID,
		arg.CycleStart,
		arg.Threshold,
	)
	var sent bool
	err := row.Scan(&sent)
	return sent, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO budget_notifications (user_id, category_id, cycle_start, threshold)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category_id, cycle_start, threshold) DO NOTHING
`

type InsertNotificationParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	CycleStart pgtype.Date `json:"cycle_start"`
	Threshold  int16       `json:"threshold"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.CategoryID,
		arg.CycleStart,
		arg.Threshold,
	)
	return err
}
