// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetCategory = `-- name: CreateBudgetCategory :one
INSERT INTO budget_categories (user_id, name, emoji, is_custom)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, emoji, is_custom, is_active, created_at
`

type CreateBudgetCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Emoji    string      `json:"emoji"`
	IsCustom bool        `json:"is_custom"`
}

func (q *Queries) CreateBudgetCategory(ctx context.Context, arg CreateBudgetCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, createBudgetCategory,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.IsCustom,
	)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.IsCustom,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetCategoryByID = `-- name: GetBudgetCategoryByID :one
SELECT id, user_id, name, emoji, is_custom, is_active, created_at FROM budget_categories
WHERE id = $1 AND user_id = $2
`

type GetBudgetCategoryByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetBudgetCategoryByID(ctx context.Context, arg GetBudgetCategoryByIDParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, getBudgetCategoryByID, arg.ID, arg.UserID)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.IsCustom,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgetCategories = `-- name: ListBudgetCategories :many
SELECT id, user_id, name, emoji, is_custom, is_active, created_at FROM budget_categories
WHERE user_id = $1
ORDER BY is_custom ASC, name ASC
`

func (q *Queries) ListBudgetCategories(ctx context.Context, userID pgtype.UUID) ([]BudgetCategory, error) {
	rows, err := q.db.Query(ctx, listBudgetCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetCategory{}
	for rows.Next() {
		var i BudgetCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Emoji,
			&i.IsCustom,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBudgetCategory = `-- name: SoftDeleteBudgetCategory :exec
UPDATE budget_categories
SET is_active = FALSE
WHERE id = $1 AND user_id = $2 AND is_custom = TRUE
`

type SoftDeleteBudgetCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteBudgetCategory(ctx context.Context, arg SoftDeleteBudgetCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteBudgetCategory, arg.ID, arg.UserID)
	return err
}
