// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDebtsSummary = `-- name: GetActiveDebtsSummary :many
SELECT id, name, total_amount, monthly_payment
FROM debts
WHERE user_id = $1 AND is_active = TRUE
`

type GetActiveDebtsSummaryRow struct {
	ID             pgtype.UUID    `json:"id"`
	Name           string         `json:"name"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	MonthlyPayment pgtype.Numeric `json:"monthly_payment"`
}

func (q *Queries) GetActiveDebtsSummary(ctx context.Context, userID pgtype.UUID) ([]GetActiveDebtsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getActiveDebtsSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveDebtsSummaryRow{}
	for rows.Next() {
		var i GetActiveDebtsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalAmount,
			&i.MonthlyPayment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveGoalsSummary = `-- name: GetActiveGoalsSummary :many
SELECT id, name, target_amount, current_amount, emoji
FROM goals
WHERE user_id = $1 AND status = 'active'
ORDER BY priority
`

type GetActiveGoalsSummaryRow struct {
	ID            pgtype.UUID    `json:"id"`
	Name          string         `json:"name"`
	TargetAmount  pgtype.Numeric `json:"target_amount"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	Emoji         pgtype.Text    `json:"emoji"`
}

func (q *Queries) GetActiveGoalsSummary(ctx context.Context, userID pgtype.UUID) ([]GetActiveGoalsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getActiveGoalsSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveGoalsSummaryRow{}
	for rows.Next() {
		var i GetActiveGoalsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Emoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT id, user_id, account_id, amount, currency, description, merchant_name, category, subcategory, value_date, is_manual, notes, created_at FROM transactions
WHERE user_id = $1
ORDER BY value_date DESC
LIMIT $2
`

type GetRecentTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.MerchantName,
			&i.Category,
			&i.Subcategory,
			&i.ValueDate,
			&i.IsManual,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalAssets = `-- name: GetTotalAssets :one
SELECT COALESCE(SUM(balance), 0)::NUMERIC AS total_assets
FROM accounts
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetTotalAssets(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalAssets, userID)
	var total_assets pgtype.Numeric
	err := row.Scan(&total_assets)
	return total_assets, err
}

const getTotalDebt = `-- name: GetTotalDebt :one
SELECT COALESCE(SUM(total_amount), 0)::NUMERIC AS total_debt
FROM debts
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetTotalDebt(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalDebt, userID)
	var total_debt pgtype.Numeric
	err := row.Scan(&total_debt)
	return total_debt, err
}
