// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, amount, description, subcategory, expense_date)
VALUES ($1, $2, $3, $5, $6, $4)
RETURNING id, user_id, category_id, amount, description, subcategory, expense_date, created_at
`

type CreateExpenseParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	Description pgtype.Text    `json:"description"`
	Subcategory pgtype.Text    `json:"subcategory"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.ExpenseDate,
		arg.Description,
		arg.Subcategory,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Subcategory,
		&i.ExpenseDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const listExpensesByCycle = `-- name: ListExpensesByCycle :many
SELECT e.id, e.user_id, e.category_id, e.amount, e.description, e.subcategory, e.expense_date, e.created_at, bc.name AS category_name, bc.emoji AS category_emoji
FROM expenses e
JOIN budget_categories bc ON bc.id = e.category_id
WHERE e.user_id = $1
  AND e.expense_date >= $2
  AND e.expense_date <= $3
ORDER BY e.expense_date DESC, e.created_at DESC
`

type ListExpensesByCycleParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type ListExpensesByCycleRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Description   pgtype.Text        `json:"description"`
	Subcategory   pgtype.Text        `json:"subcategory"`
	ExpenseDate   pgtype.Date        `json:"expense_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CategoryName  string             `json:"category_name"`
	CategoryEmoji string             `json:"category_emoji"`
}

func (q *Queries) ListExpensesByCycle(ctx context.Context, arg ListExpensesByCycleParams) ([]ListExpensesByCycleRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByCycle, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesByCycleRow{}
	for rows.Next() {
		var i ListExpensesByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Subcategory,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAllExpensesCycle = `-- name: SumAllExpensesCycle :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total_spent
FROM expenses
WHERE user_id = $1
  AND expense_date >= $2
  AND expense_date <= $3
`

type SumAllExpensesCycleParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

func (q *Queries) SumAllExpensesCycle(ctx context.Context, arg SumAllExpensesCycleParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAllExpensesCycle, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	var total_spent pgtype.Numeric
	err := row.Scan(&total_spent)
	return total_spent, err
}

const sumExpensesByCategoryCycle = `-- name: SumExpensesByCategoryCycle :many
SELECT category_id, COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total_spent
FROM expenses
WHERE user_id = $1
  AND expense_date >= $2
  AND expense_date <= $3
GROUP BY category_id
`

type SumExpensesByCategoryCycleParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type SumExpensesByCategoryCycleRow struct {
	CategoryID pgtype.UUID    `json:"category_id"`
	TotalSpent pgtype.Numeric `json:"total_spent"`
}

func (q *Queries) SumExpensesByCategoryCycle(ctx context.Context, arg SumExpensesByCategoryCycleParams) ([]SumExpensesByCategoryCycleRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategoryCycle, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryCycleRow{}
	for rows.Next() {
		var i SumExpensesByCategoryCycleRow
		if err := rows.Scan(&i.CategoryID, &i.TotalSpent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByCategoryID = `-- name: SumExpensesByCategoryID :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total_spent
FROM expenses
WHERE user_id = $1
  AND category_id = $2
  AND expense_date >= $3
  AND expense_date <= $4
`

type SumExpensesByCategoryIDParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CategoryID    pgtype.UUID `json:"category_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

func (q *Queries) SumExpensesByCategoryID(ctx context.Context, arg SumExpensesByCategoryIDParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumExpensesByCategoryID,
		arg.UserID,
		arg.CategoryID,
		arg.ExpenseDate,
		arg.ExpenseDate_2,
	)
	var total_spent pgtype.Numeric
	err := row.Scan(&total_spent)
	return total_spent, err
}
