// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :one
UPDATE users
SET full_name = $2,
    country = $3,
    birth_date = $4,
    occupation = $5,
    onboarding_done = TRUE
WHERE id = $1
RETURNING id, email, password_hash, full_name, country, birth_date, occupation, onboarding_done, plan, avatar_url, created_at, updated_at
`

type CompleteOnboardingParams struct {
	ID         pgtype.UUID `json:"id"`
	FullName   string      `json:"full_name"`
	Country    string      `json:"country"`
	BirthDate  pgtype.Date `json:"birth_date"`
	Occupation pgtype.Text `json:"occupation"`
}

func (q *Queries) CompleteOnboarding(ctx context.Context, arg CompleteOnboardingParams) (User, error) {
	row := q.db.QueryRow(ctx, completeOnboarding,
		arg.ID,
		arg.FullName,
		arg.Country,
		arg.BirthDate,
		arg.Occupation,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Country,
		&i.BirthDate,
		&i.Occupation,
		&i.OnboardingDone,
		&i.Plan,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, full_name, country, birth_date, occupation, onboarding_done, plan, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Country,
		&i.BirthDate,
		&i.Occupation,
		&i.OnboardingDone,
		&i.Plan,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, country, birth_date, occupation, onboarding_done, plan, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Country,
		&i.BirthDate,
		&i.Occupation,
		&i.OnboardingDone,
		&i.Plan,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, country, birth_date, occupation, onboarding_done, plan, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Country,
		&i.BirthDate,
		&i.Occupation,
		&i.OnboardingDone,
		&i.Plan,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = COALESCE($2, full_name),
    avatar_url = COALESCE($3, avatar_url)
WHERE id = $1
RETURNING id, email, password_hash, full_name, country, birth_date, occupation, onboarding_done, plan, avatar_url, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	FullName  pgtype.Text `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Country,
		&i.BirthDate,
		&i.Occupation,
		&i.OnboardingDone,
		&i.Plan,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
