// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, currency, balance, credit_limit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, type, currency, balance, credit_limit, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	Name        string         `json:"name"`
	Type        pgtype.Text    `json:"type"`
	Currency    string         `json:"currency"`
	Balance     pgtype.Numeric `json:"balance"`
	CreditLimit pgtype.Numeric `json:"credit_limit"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Balance,
		arg.CreditLimit,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, currency, balance, credit_limit, is_active, created_at, updated_at FROM accounts WHERE id = $1 AND user_id = $2
`

type GetAccountByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, type, currency, balance, credit_limit, is_active, created_at, updated_at FROM accounts
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Balance,
			&i.CreditLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = COALESCE($3, name),
    balance = COALESCE($4, balance),
    is_active = COALESCE($5, is_active)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, currency, balance, credit_limit, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	ID       pgtype.UUID    `json:"id"`
	UserID   pgtype.UUID    `json:"user_id"`
	Name     pgtype.Text    `json:"name"`
	Balance  pgtype.Numeric `json:"balance"`
	IsActive pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Balance,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
