// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    user_id, type, name, institution, total_amount,
    original_amount, monthly_payment, interest_rate, notes
) VALUES ($1, $2, $3, $5, $4,
    $6, $7,
    $8, $9)
RETURNING id, user_id, type, name, institution, total_amount, original_amount, monthly_payment, interest_rate, is_active, notes, created_at, updated_at
`

type CreateDebtParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	Type           string         `json:"type"`
	Name           string         `json:"name"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	Institution    pgtype.Text    `json:"institution"`
	OriginalAmount pgtype.Numeric `json:"original_amount"`
	MonthlyPayment pgtype.Numeric `json:"monthly_payment"`
	InterestRate   pgtype.Numeric `json:"interest_rate"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.TotalAmount,
		arg.Institution,
		arg.OriginalAmount,
		arg.MonthlyPayment,
		arg.InterestRate,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Institution,
		&i.TotalAmount,
		&i.OriginalAmount,
		&i.MonthlyPayment,
		&i.InterestRate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = $1 AND user_id = $2
`

type DeleteDebtParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDebt(ctx context.Context, arg DeleteDebtParams) error {
	_, err := q.db.Exec(ctx, deleteDebt, arg.ID, arg.UserID)
	return err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, user_id, type, name, institution, total_amount, original_amount, monthly_payment, interest_rate, is_active, notes, created_at, updated_at FROM debts WHERE id = $1 AND user_id = $2
`

type GetDebtByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDebtByID(ctx context.Context, arg GetDebtByIDParams) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, arg.ID, arg.UserID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Institution,
		&i.TotalAmount,
		&i.OriginalAmount,
		&i.MonthlyPayment,
		&i.InterestRate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDebts = `-- name: ListDebts :many
SELECT id, user_id, type, name, institution, total_amount, original_amount, monthly_payment, interest_rate, is_active, notes, created_at, updated_at FROM debts
WHERE user_id = $1
  AND ($2::BOOLEAN IS NULL OR is_active = $2)
ORDER BY created_at DESC
`

type ListDebtsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ActiveOnly pgtype.Bool `json:"active_only"`
}

func (q *Queries) ListDebts(ctx context.Context, arg ListDebtsParams) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebts, arg.UserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Institution,
			&i.TotalAmount,
			&i.OriginalAmount,
			&i.MonthlyPayment,
			&i.InterestRate,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts
SET type = COALESCE($3, type),
    name = COALESCE($4, name),
    institution = COALESCE($5, institution),
    total_amount = COALESCE($6, total_amount),
    original_amount = COALESCE($7, original_amount),
    monthly_payment = COALESCE($8, monthly_payment),
    interest_rate = COALESCE($9, interest_rate),
    is_active = COALESCE($10, is_active),
    notes = COALESCE($11, notes)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, institution, total_amount, original_amount, monthly_payment, interest_rate, is_active, notes, created_at, updated_at
`

type UpdateDebtParams struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	Type           pgtype.Text    `json:"type"`
	Name           pgtype.Text    `json:"name"`
	Institution    pgtype.Text    `json:"institution"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	OriginalAmount pgtype.Numeric `json:"original_amount"`
	MonthlyPayment pgtype.Numeric `json:"monthly_payment"`
	InterestRate   pgtype.Numeric `json:"interest_rate"`
	IsActive       pgtype.Bool    `json:"is_active"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebt,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Institution,
		arg.TotalAmount,
		arg.OriginalAmount,
		arg.MonthlyPayment,
		arg.InterestRate,
		arg.IsActive,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Institution,
		&i.TotalAmount,
		&i.OriginalAmount,
		&i.MonthlyPayment,
		&i.InterestRate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
