// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE fcm_token = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDevice, fcmToken)
	return err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, fcm_token, platform, created_at FROM devices WHERE user_id = $1
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, fcm_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform
`

type UpsertDeviceParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FcmToken string      `json:"fcm_token"`
	Platform string      `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice, arg.UserID, arg.FcmToken, arg.Platform)
	return err
}
