// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addContribution = `-- name: AddContribution :one
UPDATE goals
SET current_amount = current_amount + $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, target_amount, current_amount, monthly_contribution, target_date, priority, status, emoji, notes, created_at, updated_at
`

type AddContributionParams struct {
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
}

func (q *Queries) AddContribution(ctx context.Context, arg AddContributionParams) (Goal, error) {
	row := q.db.QueryRow(ctx, addContribution, arg.ID, arg.UserID, arg.CurrentAmount)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.MonthlyContribution,
		&i.TargetDate,
		&i.Priority,
		&i.Status,
		&i.Emoji,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
    user_id, type, name, target_amount, monthly_contribution,
    target_date, priority, emoji, notes
) VALUES ($1, $2, $3, $4, $6,
    $7, $5, $8, $9)
RETURNING id, user_id, type, name, target_amount, current_amount, monthly_contribution, target_date, priority, status, emoji, notes, created_at, updated_at
`

type CreateGoalParams struct {
	UserID              pgtype.UUID    `json:"user_id"`
	Type                string         `json:"type"`
	Name                string         `json:"name"`
	TargetAmount        pgtype.Numeric `json:"target_amount"`
	Priority            int16          `json:"priority"`
	MonthlyContribution pgtype.Numeric `json:"monthly_contribution"`
	TargetDate          pgtype.Date    `json:"target_date"`
	Emoji               pgtype.Text    `json:"emoji"`
	Notes               pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.TargetAmount,
		arg.Priority,
		arg.MonthlyContribution,
		arg.TargetDate,
		arg.Emoji,
		arg.Notes,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.MonthlyContribution,
		&i.TargetDate,
		&i.Priority,
		&i.Status,
		&i.Emoji,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, user_id, type, name, target_amount, current_amount, monthly_contribution, target_date, priority, status, emoji, notes, created_at, updated_at FROM goals WHERE id = $1 AND user_id = $2
`

type GetGoalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoalByID, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.MonthlyContribution,
		&i.TargetDate,
		&i.Priority,
		&i.Status,
		&i.Emoji,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, type, name, target_amount, current_amount, monthly_contribution, target_date, priority, status, emoji, notes, created_at, updated_at FROM goals
WHERE user_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
ORDER BY priority, created_at DESC
`

type ListGoalsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.MonthlyContribution,
			&i.TargetDate,
			&i.Priority,
			&i.Status,
			&i.Emoji,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = COALESCE($3, name),
    target_amount = COALESCE($4, target_amount),
    current_amount = COALESCE($5, current_amount),
    monthly_contribution = COALESCE($6, monthly_contribution),
    status = COALESCE($7, status),
    emoji = COALESCE($8, emoji),
    notes = COALESCE($9, notes)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, target_amount, current_amount, monthly_contribution, target_date, priority, status, emoji, notes, created_at, updated_at
`

type UpdateGoalParams struct {
	ID                  pgtype.UUID    `json:"id"`
	UserID              pgtype.UUID    `json:"user_id"`
	Name                pgtype.Text    `json:"name"`
	TargetAmount        pgtype.Numeric `json:"target_amount"`
	CurrentAmount       pgtype.Numeric `json:"current_amount"`
	MonthlyContribution pgtype.Numeric `json:"monthly_contribution"`
	Status              pgtype.Text    `json:"status"`
	Emoji               pgtype.Text    `json:"emoji"`
	Notes               pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.MonthlyContribution,
		arg.Status,
		arg.Emoji,
		arg.Notes,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.MonthlyContribution,
		&i.TargetDate,
		&i.Priority,
		&i.Status,
		&i.Emoji,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
