// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (
    user_id, name, institution, type, amount_invested, current_value, notes
) VALUES ($1, $2, $6, $3, $4, $5, $7)
RETURNING id, user_id, name, institution, type, amount_invested, current_value, notes, is_active, created_at, updated_at
`

type CreateInvestmentParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	Name           string         `json:"name"`
	Type           string         `json:"type"`
	AmountInvested pgtype.Numeric `json:"amount_invested"`
	CurrentValue   pgtype.Numeric `json:"current_value"`
	Institution    pgtype.Text    `json:"institution"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.AmountInvested,
		arg.CurrentValue,
		arg.Institution,
		arg.Notes,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.AmountInvested,
		&i.CurrentValue,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvestment = `-- name: DeleteInvestment :exec
DELETE FROM investments WHERE id = $1 AND user_id = $2
`

type DeleteInvestmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteInvestment(ctx context.Context, arg DeleteInvestmentParams) error {
	_, err := q.db.Exec(ctx, deleteInvestment, arg.ID, arg.UserID)
	return err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, user_id, name, institution, type, amount_invested, current_value, notes, is_active, created_at, updated_at FROM investments WHERE id = $1 AND user_id = $2
`

type GetInvestmentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetInvestmentByID(ctx context.Context, arg GetInvestmentByIDParams) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, arg.ID, arg.UserID)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.AmountInvested,
		&i.CurrentValue,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvestments = `-- name: ListInvestments :many
SELECT id, user_id, name, institution, type, amount_invested, current_value, notes, is_active, created_at, updated_at FROM investments
WHERE user_id = $1
  AND ($2::BOOLEAN IS NULL OR is_active = $2)
ORDER BY created_at DESC
`

type ListInvestmentsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ActiveOnly pgtype.Bool `json:"active_only"`
}

func (q *Queries) ListInvestments(ctx context.Context, arg ListInvestmentsParams) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestments, arg.UserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Institution,
			&i.Type,
			&i.AmountInvested,
			&i.CurrentValue,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvestment = `-- name: UpdateInvestment :one
UPDATE investments
SET name = COALESCE($3, name),
    institution = COALESCE($4, institution),
    type = COALESCE($5, type),
    amount_invested = COALESCE($6, amount_invested),
    current_value = COALESCE($7, current_value),
    is_active = COALESCE($8, is_active),
    notes = COALESCE($9, notes)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, institution, type, amount_invested, current_value, notes, is_active, created_at, updated_at
`

type UpdateInvestmentParams struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	Name           pgtype.Text    `json:"name"`
	Institution    pgtype.Text    `json:"institution"`
	Type           pgtype.Text    `json:"type"`
	AmountInvested pgtype.Numeric `json:"amount_invested"`
	CurrentValue   pgtype.Numeric `json:"current_value"`
	IsActive       pgtype.Bool    `json:"is_active"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, updateInvestment,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Institution,
		arg.Type,
		arg.AmountInvested,
		arg.CurrentValue,
		arg.IsActive,
		arg.Notes,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.AmountInvested,
		&i.CurrentValue,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
