// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Type        pgtype.Text        `json:"type"`
	Currency    string             `json:"currency"`
	Balance     pgtype.Numeric     `json:"balance"`
	CreditLimit pgtype.Numeric     `json:"credit_limit"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AiConversation struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Title           pgtype.Text        `json:"title"`
	Messages        []byte             `json:"messages"`
	ContextSnapshot []byte             `json:"context_snapshot"`
	MessageCount    int32              `json:"message_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Budget struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	GlobalAmount  pgtype.Numeric     `json:"global_amount"`
	CycleStartDay int16              `json:"cycle_start_day"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BudgetAllocation struct {
	ID         pgtype.UUID        `json:"id"`
	BudgetID   pgtype.UUID        `json:"budget_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type BudgetCategory struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Emoji     string             `json:"emoji"`
	IsCustom  bool               `json:"is_custom"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BudgetNotification struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CycleStart pgtype.Date        `json:"cycle_start"`
	Threshold  int16              `json:"threshold"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
}

type Debt struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Institution    pgtype.Text        `json:"institution"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	OriginalAmount pgtype.Numeric     `json:"original_amount"`
	MonthlyPayment pgtype.Numeric     `json:"monthly_payment"`
	InterestRate   pgtype.Numeric     `json:"interest_rate"`
	IsActive       bool               `json:"is_active"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FcmToken  string             `json:"fcm_token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Subcategory pgtype.Text        `json:"subcategory"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Goal struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Type                string             `json:"type"`
	Name                string             `json:"name"`
	TargetAmount        pgtype.Numeric     `json:"target_amount"`
	CurrentAmount       pgtype.Numeric     `json:"current_amount"`
	MonthlyContribution pgtype.Numeric     `json:"monthly_contribution"`
	TargetDate          pgtype.Date        `json:"target_date"`
	Priority            int16              `json:"priority"`
	Status              string             `json:"status"`
	Emoji               pgtype.Text        `json:"emoji"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Investment struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	Institution    pgtype.Text        `json:"institution"`
	Type           string             `json:"type"`
	AmountInvested pgtype.Numeric     `json:"amount_invested"`
	CurrentValue   pgtype.Numeric     `json:"current_value"`
	Notes          pgtype.Text        `json:"notes"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	Amount       pgtype.Numeric     `json:"amount"`
	Currency     string             `json:"currency"`
	Description  pgtype.Text        `json:"description"`
	MerchantName pgtype.Text        `json:"merchant_name"`
	Category     pgtype.Text        `json:"category"`
	Subcategory  pgtype.Text        `json:"subcategory"`
	ValueDate    pgtype.Date        `json:"value_date"`
	IsManual     bool               `json:"is_manual"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FullName       string             `json:"full_name"`
	Country        string             `json:"country"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	Occupation     pgtype.Text        `json:"occupation"`
	OnboardingDone bool               `json:"onboarding_done"`
	Plan           string             `json:"plan"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
