// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, account_id, amount, currency, description,
    merchant_name, category, subcategory, value_date, is_manual, notes
) VALUES ($1, $6, $2, $3, $7,
    $8, $9, $10,
    $4, $5, $11)
RETURNING id, user_id, account_id, amount, currency, description, merchant_name, category, subcategory, value_date, is_manual, notes, created_at
`

type CreateTransactionParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	Amount       pgtype.Numeric `json:"amount"`
	Currency     string         `json:"currency"`
	ValueDate    pgtype.Date    `json:"value_date"`
	IsManual     bool           `json:"is_manual"`
	AccountID    pgtype.UUID    `json:"account_id"`
	Description  pgtype.Text    `json:"description"`
	MerchantName pgtype.Text    `json:"merchant_name"`
	Category     pgtype.Text    `json:"category"`
	Subcategory  pgtype.Text    `json:"subcategory"`
	Notes        pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.ValueDate,
		arg.IsManual,
		arg.AccountID,
		arg.Description,
		arg.MerchantName,
		arg.Category,
		arg.Subcategory,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.MerchantName,
		&i.Category,
		&i.Subcategory,
		&i.ValueDate,
		&i.IsManual,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
    COALESCE(category, 'Sin categoría') AS category,
    COALESCE(SUM(ABS(amount)), 0)::NUMERIC AS total,
    COUNT(*)::BIGINT AS tx_count
FROM transactions
WHERE user_id = $1
  AND amount < 0
  AND value_date >= DATE_TRUNC('month', $2::DATE)
  AND value_date < DATE_TRUNC('month', $2::DATE) + INTERVAL '1 month'
GROUP BY category
ORDER BY total DESC
`

type GetCategoryBreakdownParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type GetCategoryBreakdownRow struct {
	Category string         `json:"category"`
	Total    pgtype.Numeric `json:"total"`
	TxCount  int64          `json:"tx_count"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreakdownRow{}
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Total, &i.TxCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE amount > 0), 0)::NUMERIC AS income,
    COALESCE(SUM(ABS(amount)) FILTER (WHERE amount < 0), 0)::NUMERIC AS expenses,
    COALESCE(SUM(amount), 0)::NUMERIC AS net,
    COUNT(*)::BIGINT AS tx_count
FROM transactions
WHERE user_id = $1
  AND value_date >= DATE_TRUNC('month', $2::DATE)
  AND value_date < DATE_TRUNC('month', $2::DATE) + INTERVAL '1 month'
`

type GetMonthlySummaryParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type GetMonthlySummaryRow struct {
	Income   pgtype.Numeric `json:"income"`
	Expenses pgtype.Numeric `json:"expenses"`
	Net      pgtype.Numeric `json:"net"`
	TxCount  int64          `json:"tx_count"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary, arg.UserID, arg.Column2)
	var i GetMonthlySummaryRow
	err := row.Scan(
		&i.Income,
		&i.Expenses,
		&i.Net,
		&i.TxCount,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, account_id, amount, currency, description, merchant_name, category, subcategory, value_date, is_manual, notes, created_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.MerchantName,
		&i.Category,
		&i.Subcategory,
		&i.ValueDate,
		&i.IsManual,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, amount, currency, description, merchant_name, category, subcategory, value_date, is_manual, notes, created_at FROM transactions
WHERE user_id = $1
  AND ($4::TEXT IS NULL OR category = $4)
ORDER BY value_date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.MerchantName,
			&i.Category,
			&i.Subcategory,
			&i.ValueDate,
			&i.IsManual,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount = COALESCE($3, amount),
    description = COALESCE($4, description),
    category = COALESCE($5, category),
    notes = COALESCE($6, notes)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, account_id, amount, currency, description, merchant_name, category, subcategory, value_date, is_manual, notes, created_at
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID    `json:"id"`
	UserID      pgtype.UUID    `json:"user_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description pgtype.Text    `json:"description"`
	Category    pgtype.Text    `json:"category"`
	Notes       pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.Category,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.MerchantName,
		&i.Category,
		&i.Subcategory,
		&i.ValueDate,
		&i.IsManual,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
